[versions]
agp = "8.10.1"

#android
appcompat = "1.0.0"
recyclerview = "1.0.0"
cardview = "1.0.0"
lifecycleextensions = "2.0.0"
lifecyclecompiler = "2.0.0"

material = "1.0.0"

#Core
playServicesMaps = "19.2.0"
retrofit = "2.5.0"
room = "2.0.0"
dagger = "2.56"
eventbus = "3.3.1"
guava = "33.4.8-android"
materialdrawer = "2.9.8"
okhttp = "4.12.0"
rxandroid = "2.1.1"
rxjava = "2.2.6"
socketIoClient = "2.1.2"
gson = "2.8.5"

jacksonCore = "2.4.1"

desugar_jdk_libs = "2.0.3"

#testing
testcore = "1.6.1"
junit = "4.13.2"

#junitVersion = "1.2.1"
#espressoCore = "3.6.1"
#appcompat = "1.6.1"
#material = "1.10.0"
#constraintlayout = "2.1.4"
#lifecycleLivedataKtx = "2.9.0"
#lifecycleViewmodelKtx = "2.9.0"
#navigationFragment = "2.6.0"
#navigationUi = "2.6.0"

[libraries]

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
material = { module = "com.google.android.material:material", version.ref = "material" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
lifecycleextensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleextensions" }
lifecyclecompiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecyclecompiler" }

dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
daggercompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
materialdrawer = { module = "com.mikepenz.materialdrawer:library", version.ref = "materialdrawer" }
socketioclient = { module = "io.socket:socket.io-client", version.ref = "socketIoClient" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

retrofitconvertergson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }

roomruntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomcompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomrxjava2 = { module = "androidx.room:room-rxjava2", version.ref = "room" }

jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonCore" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jacksonCore" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonCore" }

desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }


testcore = { module = "androidx.test:core", version.ref = "testcore" }
junit-junit = { module = "junit:junit", version.ref = "junit" }

#ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
#lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
#navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
#navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

