plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.tom.meeter'
    compileSdk 35

    defaultConfig {
        applicationId "com.tom.meeter"
        minSdk 21
        targetSdk 35
        versionCode 1
        versionName "1.0"

        /*
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        */
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        //LocalDateTime features
        coreLibraryDesugaringEnabled = true

        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        viewBinding true
    }

    lint {
        baseline = file("lint-baseline.xml")
    }
}
dependencies {

    implementation libs.appcompat
    implementation libs.recyclerview
    implementation libs.material
    implementation libs.cardview

    implementation libs.lifecycle.extensions
    annotationProcessor libs.lifecycle.compiler

    implementation libs.socketioclient
    implementation libs.eventbus

    implementation libs.play.services.maps

    implementation (libs.materialdrawer)
    // https://mvnrepository.com/artifact/com.mikepenz/fontawesome-typeface
    implementation("com.mikepenz:fontawesome-typeface:5.3.1.1")
    //try it
    // https://mvnrepository.com/artifact/com.mikepenz/google-material-typeface
    implementation("com.mikepenz:google-material-typeface:3.0.1.3.original")

    implementation libs.rxandroid
    implementation libs.rxjava

    implementation libs.jackson.core
    implementation libs.jackson.annotations
    implementation libs.jackson.databind

    /*implementation 'androidx.lifecycle:lifecycle-viewmodel:2.0.0'*/

    // Retrofit & OkHttp
    implementation libs.retrofit
    implementation libs.retrofit.converter.jackson
    //implementation libs.retrofitconvertergson
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310
    implementation(libs.jackson.datatype.jsr310)
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jdk8
    implementation(libs.jackson.datatype.jdk8)

    implementation libs.okhttp

    // Dagger 2
    implementation libs.dagger
    annotationProcessor libs.dagger.compiler

    // Room
    implementation libs.room.runtime
    implementation libs.room.rxjava2
    annotationProcessor libs.room.compiler


    //LocalDateTime features
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation libs.guava

    // https://mvnrepository.com/artifact/androidx.preference/preference
    implementation libs.preference

    implementation libs.core


    /*TESTS*/

    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    //androidTestImplementation "androidx.compose.ui:ui-test-junit4:1.0.4"
    androidTestImplementation libs.testcore


    testImplementation(libs.junit.junit)
    //testImplementation("org.powermock:powermock-module-junit4:2.0.9")
}


