#Backend section
server.ip=192.168.61.59
server.port=8084
server.io_port=8085

#Map section
#meters
map.events_area=1000
map.track_user=true

#Location section
#meters
location.distance=10
#milliseconds
location.time=3000
